---

- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
  - name: Update APT Repositories
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present

  tasks:
    - import_tasks: tasks/core-packages.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/vlc.yml
    - import_tasks: tasks/libreoffice.yml
    - import_tasks: tasks/sqlite3.yml
      when: install_sqlite3
    - import_tasks: tasks/vscode.yml
      when: install_vscode
    - import_tasks: tasks/neovim.yml
      when: install_neovim
