---
- hosts: localhost
  connection: local

  vars_files:
    - default.config.yml
    - vars/pip.yml
    - vars/vscode-extensions.yml

  pre_tasks:
  - name: Update APT Repositories
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present

  tasks:
    - name: Install Core Packages
      ansible.builtin.import_tasks: tasks/core-packages.yml
      tags: ['core']

    - name: Install Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Install Tmux
      ansible.builtin.import_tasks: tasks/tmux.yml
      tags: ['tmux']
      when: install_tmux

    - name: Install Pip Packages
      ansible.builtin.import_tasks: tasks/pip.yml
      tags: ['pip']
      when: install_pip

    - name: Install VS Code
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: ['vscode']
      when: install_vscode

    - name: Install Neovim
      ansible.builtin.import_tasks: tasks/neovim.yml
      tags: ['neovim']
      when: install_neovim

    - name: Install Rust
      ansible.builtin.import_tasks: tasks/rust.yml
      tags: ['rust']
      when: install_rust

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/docker.yml
      tags: ['docker']
      when: install_docker

    - name: Install VLC 
      ansible.builtin.import_tasks: tasks/vlc.yml
      tags: ['vlc']
      when: install_vlc

    - name: Install LibreOffice
      ansible.builtin.import_tasks: tasks/libreoffice.yml
      tags: ['libreoffice']
      when: install_libreoffice

    - name: Install SQLite3
      ansible.builtin.import_tasks: tasks/sqlite3.yml
      tags: ['sqlite3']
      when: install_sqlite3