- name: "core: Install Text Editor Packages (nano, vim)"
  become: true
  apt:
    name: ["nano", "vim"]
  tags:
    - install
    - core

- name: "core: Install Terminal Packages (picocom, tmux, tree, stow, fzf, tldr)"
  become: true
  apt:
    name: ["picocom", "tmux", "tree", "stow", "fzf", "tldr"]
  tags:
    - install
    - core

- name: "core: Install Networking Packages (curl, nmap)"
  become: true
  apt:
    name: ["curl", "nmap"]
  tags:
    - install
    - core

- name: "core: Install Browser Packages (firefox)"
  become: true
  apt:
    name: "firefox"
  tags:
    - install
    - core

- name: "core: Install Version Control Packages (git, svn)"
  become: true
  apt:
    name: ["git", "subversion"]
  tags:
    - install
    - core

- name: "core: Install Software Development Packages (build-essential, gcc, make, cmake, pkg-config, device-tree-compiler, u-boot-tools)"
  become: true
  apt:
    name: ["build-essential", "gcc", "make", "cmake", "pkg-config", "device-tree-compiler", "u-boot-tools"]
  tags:
    - install
    - core

- name: "core: Install Software Debugging Packages (gdb, gdb-multiarch, strace)"
  become: true
  apt:
    name: ["gdb", "gdb-multiarch", "strace"]
  tags:
    - install
    - core

- name: "core: Install Software Profiling Packages (oprofile, lttng-tools, valgrind)"
  become: true
  apt:
    name: ["oprofile", "lttng-tools", "valgrind"]
  tags:
    - install
    - core

- name: "core: Install Software Code Quality Packages (cppcheck, spellcheck, meld, doxygen, python3-sphinx)"
  become: true
  apt:
    name: ["cppcheck", "shellcheck", "meld", "doxygen", "python3-sphinx"]
  tags:
    - install
    - core
