---
- name: "dotfiles: clone .dotfiles"
  ansible.builtin.git:
    repo: 'git@github.com:tmoore3/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: "dotfiles: stow dotfiles"
  shell: cd $HOME/.dotfiles && ./install
