---
- name: "check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: "Download Installer"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  when: cargo_exists is failed

# - name: "install rust/cargo"
#   when: cargo_exists is failed
#   shell: /tmp/sh.rustup.rs -y
#   tags:
#     - rust