---
- name: "tmux: Install tmux package"
  become: true
  ansible.builtin.apt:
    name: tmux
    state: latest

- name: "tmux: Install tmux plugin manager"
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"