- name: "vscode: Install dependencies"
  tags: vscode
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present

- name: "vscode: Create APT keyrings dir"
  tags: vscode
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: "vscode: Install key"
  tags: vscode
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: true

- name: "vscode: Install VS Code repo"
  tags: vscode
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present

- name: "vscode: Install VS Code"
  tags: vscode
  become: true
  ansible.builtin.apt:
    name: "code"
    state: present

# Extensions

# Markdown
- name: "vscode: Install vscode extension Markdown Previewer"
  tags: vscode
  register: result
  shell: code --install-extension bierner.markdown-preview-github-styles
  changed_when: '"successfully installed" in result.stdout'

# XMl
- name: "vscode: Install vscode extension XML"
  tags: vscode
  register: result
  shell: code --install-extension redhat.vscode-xml
  changed_when: '"successfully installed" in result.stdout'

# YAML
- name: "vscode: Install vscode extension YAML"
  tags: vscode
  register: result
  shell: code --install-extension redhat.vscode-yaml
  changed_when: '"successfully installed" in result.stdout'

# Ansible
- name: "vscode: Install vscode extension Ansible"
  tags: vscode
  register: result
  shell: code --install-extension redhat.ansible
  changed_when: '"successfully installed" in result.stdout'

# Python
- name: "vscode: Install vscode extension Python"
  tags: vscode
  register: result
  shell: code --install-extension ms-python.python
  changed_when: '"successfully installed" in result.stdout'

- name: "vscode: Install vscode extension Pylance"
  tags: vscode
  register: result
  shell: code --install-extension ms-python.vscode-pylance
  changed_when: '"successfully installed" in result.stdout'

- name: "vscode: Install vscode extension Pylint"
  tags: vscode
  register: result
  shell: code --install-extension ms-python.pylint
  changed_when: '"successfully installed" in result.stdout'

# IntelliCode
- name: "vscode: Install vscode extension IntelliCode"
  tags: vscode
  register: result
  shell: code --install-extension VisualStudioExptTeam.vscodeintellicode
  changed_when: '"successfully installed" in result.stdout'

- name: "vscode: Install vscode extension IntelliCode API"
  tags: vscode
  register: result
  shell: code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
  changed_when: '"successfully installed" in result.stdout'

# C
- name: "vscode: Install vscode extension C/C++"
  tags: vscode
  register: result
  shell: code --install-extension ms-vscode.cpptools
  changed_when: '"successfully installed" in result.stdout'

- name: "vscode: Install vscode extension C/C++ Extension Pack"
  tags: vscode
  register: result
  shell: code --install-extension ms-vscode.cpptools-extension-pack
  changed_when: '"successfully installed" in result.stdout'

- name: "vscode: Install vscode extension C/C++ Themes"
  tags: vscode
  register: result
  shell: code --install-extension ms-vscode.cpptools-themes
  changed_when: '"successfully installed" in result.stdout'

# Makefile
- name: "vscode: Install vscode extension Makefile Tools"
  tags: vscode
  register: result
  shell: code --install-extension ms-vscode.makefile-tools
  changed_when: '"successfully installed" in result.stdout'

# CMake
- name: "vscode: Install vscode extension CMake Tools"
  tags: vscode
  register: result
  shell: code --install-extension ms-vscode.cmake-tools
  changed_when: '"successfully installed" in result.stdout'
