---
- name: "vscode: Add vscode apt key"
  ansible.builtin.apt_key:
    url: "{{ vscode_apt_key_url }}"
    keyring: "{{ vscode_apt_key_keyring }}"

- name: "vscode: Add vscode repo"
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ vscode_repo }}"
    filename: vscode
    state: present

- name: "vscode: Install vscode"
  become: true
  ansible.builtin.apt:
    name: "code"
    state: present

- name: "vscode: Install vscode extensions"
  ansible.builtin.command: "code --install-extension '{{ item }}'"
  with_items: "{{ vscode_extensions_ids }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"